import { MongoClient } from "mongodb";

const MONGO_URL = "mongodb+srv://romanjeeva22_db_user:9rKpamXN134npwzC@cluster0.chbka5j.mongodb.net/kitchen?retryWrites=true&w=majority&appName=Cluster0";

const client = new MongoClient(MONGO_URL);

const sampleRecipes = [
  {
    title: "Chicken Biryani",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800",
    video: "",
    discription: "Aromatic and flavorful rice dish with tender chicken marinated in yogurt and spices",
    main_content: "chicken",
    cuisines: "indian",
    meals: "lunch",
    cookingtime: "1 hr",
    servings: 4,
    note: "Best served with raita and mirchi ka salan",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Marinate chicken with yogurt and biryani masala for 2 hours", "Soak basmati rice for 30 minutes", "Fry onions until golden brown", "Layer rice and chicken in a pot", "Add saffron milk and dum cook on low flame for 20 mins"],
    ingredients: ["1 kg chicken", "500g basmati rice", "2 large onions", "1 cup yogurt", "Biryani masala", "Saffron strands", "Mint leaves", "Ginger garlic paste"]
  },
  {
    title: "Butter Chicken",
    image: "https://images.unsplash.com/photo-1603894584373-5c82c3e9a865?w=800",
    video: "",
    discription: "Rich and creamy tomato-based curry with tender chicken pieces",
    main_content: "chicken",
    cuisines: "indian",
    meals: "dinner",
    cookingtime: "45mins",
    servings: 4,
    note: "Add cream for extra richness and smooth texture",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Marinate chicken in tandoori masala", "Grill or pan-fry chicken until charred", "Make tomato gravy with butter and cream", "Add spices and simmer", "Mix chicken pieces and cook together"],
    ingredients: ["500g chicken", "1 cup tomato puree", "100g butter", "200ml cream", "Garam masala", "Kashmiri red chili powder", "Ginger garlic paste"]
  },
  {
    title: "Palak Paneer",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800",
    video: "",
    discription: "Creamy spinach curry with soft paneer cubes",
    main_content: "paneer",
    cuisines: "indian",
    meals: "lunch",
    cookingtime: "40mins",
    servings: 4,
    note: "Blanch spinach to retain green color",
    rating: "⭐⭐⭐⭐",
    directions: ["Blanch spinach and make puree", "Fry paneer cubes until golden", "Make onion-tomato base", "Add spinach puree and cream", "Add paneer and simmer"],
    ingredients: ["250g paneer", "500g spinach", "1 cup cream", "Onion", "Tomatoes", "Ginger garlic paste", "Garam masala"]
  },
  {
    title: "Margherita Pizza",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    video: "",
    discription: "Classic Italian pizza with fresh mozzarella, tomatoes and basil",
    main_content: "pizza dough",
    cuisines: "italian",
    meals: "dinner",
    cookingtime: "30mins",
    servings: 2,
    note: "Use fresh mozzarella and authentic Italian tomatoes",
    rating: "⭐⭐⭐⭐",
    directions: ["Make pizza dough with flour and yeast", "Spread tomato sauce evenly", "Add torn mozzarella pieces", "Bake at 400°F for 15-20 mins", "Top with fresh basil leaves"],
    ingredients: ["2 cups all-purpose flour", "1 cup fresh mozzarella", "Tomato sauce", "Fresh basil leaves", "Olive oil", "Salt"]
  },
  {
    title: "Spaghetti Carbonara",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800",
    video: "",
    discription: "Creamy Roman pasta with eggs, cheese, and crispy guanciale",
    main_content: "pasta",
    cuisines: "italian",
    meals: "dinner",
    cookingtime: "25mins",
    servings: 4,
    note: "Use room temperature eggs for creamy texture",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Cook spaghetti until al dente", "Mix eggs with pecorino and pepper", "Crisp guanciale in pan", "Toss hot pasta with egg mixture off heat", "Add guanciale and serve"],
    ingredients: ["400g spaghetti", "4 egg yolks", "100g pecorino romano", "150g guanciale", "Black pepper", "Salt"]
  },
  {
    title: "Caesar Salad",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800",
    video: "",
    discription: "Crispy romaine lettuce with creamy Caesar dressing and parmesan",
    main_content: "romaine lettuce",
    cuisines: "italian",
    meals: "lunch",
    cookingtime: "15mins",
    servings: 2,
    note: "Add homemade croutons for extra crunch",
    rating: "⭐⭐⭐⭐",
    directions: ["Wash and chop romaine lettuce", "Prepare Caesar dressing", "Toss lettuce with dressing", "Add shaved parmesan", "Top with crispy croutons"],
    ingredients: ["1 head romaine lettuce", "Caesar dressing", "Parmesan cheese", "Croutons", "Black pepper", "Anchovy optional"]
  },
  {
    title: "Tacos Al Pastor",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800",
    video: "",
    discription: "Mexican street tacos with marinated pork and pineapple",
    main_content: "pork",
    cuisines: "mexican",
    meals: "dinner",
    cookingtime: "1 hr",
    servings: 6,
    note: "Best with fresh corn tortillas",
    rating: "⭐⭐⭐⭐",
    directions: ["Marinate pork in adobo spices", "Grill pork with pineapple", "Chop meat into small pieces", "Warm corn tortillas", "Top with onion, cilantro and lime"],
    ingredients: ["500g pork shoulder", "Achiote paste", "Pineapple", "Corn tortillas", "Onion", "Cilantro", "Lime", "Guacamole"]
  },
  {
    title: "Chicken Enchiladas",
    image: "https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800",
    video: "",
    discription: "Rolled tortillas filled with chicken and smothered in sauce",
    main_content: "chicken",
    cuisines: "mexican",
    meals: "lunch",
    cookingtime: "45mins",
    servings: 4,
    note: "Make extra sauce for topping",
    rating: "⭐⭐⭐⭐",
    directions: ["Shred cooked chicken", "Make enchilada sauce", "Fill tortillas with chicken and cheese", "Roll and place in baking dish", "Cover with sauce and bake"],
    ingredients: ["12 corn tortillas", "2 cups shredded chicken", "Red enchilada sauce", "Cheddar cheese", "Onion", "Sour cream"]
  },
  {
    title: "Guacamole",
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800",
    video: "",
    discription: "Fresh avocado dip with lime and cilantro",
    main_content: "avocado",
    cuisines: "mexican",
    meals: "snacks",
    cookingtime: "10mins",
    servings: 4,
    note: "Add jalapeño for extra heat",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Cut and mash avocados", "Add lime juice immediately", "Mix in diced onion and tomato", "Add cilantro and salt", "Serve with tortilla chips"],
    ingredients: ["3 ripe avocados", "1 lime", "1/2 onion", "2 tomatoes", "Fresh cilantro", "Salt", "Jalapeño optional"]
  },
  {
    title: "Kung Pao Chicken",
    image: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800",
    video: "",
    discription: "Spicy Sichuan stir-fry with peanuts and dried chilies",
    main_content: "chicken",
    cuisines: "chinese",
    meals: "dinner",
    cookingtime: "30mins",
    servings: 3,
    note: "Adjust spice level to taste",
    rating: "⭐⭐⭐⭐",
    directions: ["Cut and marinate chicken", "Stir-fry peanuts and set aside", "Cook chicken until done", "Add vegetables and sauce", "Mix peanuts back in"],
    ingredients: ["300g chicken breast", "Peanuts", "Dried chilies", "Sichuan peppercorns", "Soy sauce", "Vinegar", "Spring onion", "Garlic"]
  },
  {
    title: "Fried Rice",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800",
    video: "",
    discription: "Quick and delicious Asian rice dish with vegetables and eggs",
    main_content: "rice",
    cuisines: "chinese",
    meals: "lunch",
    cookingtime: "20mins",
    servings: 3,
    note: "Use day-old cold rice for best results",
    rating: "⭐⭐⭐⭐",
    directions: ["Heat wok on high flame", "Scramble eggs first and set aside", "Stir-fry vegetables", "Add rice and toss", "Add soy sauce and mix well"],
    ingredients: ["3 cups cooked rice", "2 eggs", "Soy sauce", "Mixed vegetables", "Green onion", "Sesame oil", "Garlic"]
  },
  {
    title: "Dim Sum Dumplings",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800",
    video: "",
    discription: "Steamed dumplings filled with pork and vegetables",
    main_content: "pork",
    cuisines: "chinese",
    meals: "lunch",
    cookingtime: "1 hr",
    servings: 6,
    note: "Freeze extra for later",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Make dumpling wrappers", "Prepare pork filling", "Fill and fold dumplings", "Steam for 8-10 minutes", "Serve with dipping sauce"],
    ingredients: ["2 cups flour", "250g ground pork", "Shrimp", "Napa cabbage", "Soy sauce", "Ginger", "Sesame oil"]
  },
  {
    title: "Sushi Roll",
    image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
    video: "",
    discription: "Japanese delicacy with vinegared rice and fresh fish",
    main_content: "sushi rice",
    cuisines: "japanese",
    meals: "lunch",
    cookingtime: "45mins",
    servings: 4,
    note: "Use fresh fish and proper sushi rice",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Prepare sushi rice with vinegar", "Place nori sheet on bamboo mat", "Spread rice evenly", "Add fish and vegetables", "Roll tightly and cut"],
    ingredients: ["2 cups sushi rice", "Nori sheets", "Fresh salmon or tuna", "Cucumber", "Avocado", "Rice vinegar", "Soy sauce"]
  },
  {
    title: "Ramen Noodles",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
    video: "",
    discription: "Rich pork bone broth with fresh noodles and toppings",
    main_content: "ramen noodles",
    cuisines: "japanese",
    meals: "dinner",
    cookingtime: "2 hrs",
    servings: 4,
    note: "Slow simmer broth for best flavor",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Simmer pork bones for broth", "Prepare tare (seasoning base)", "Cook ramen noodles", "Assemble bowl with toppings", "Serve immediately"],
    ingredients: ["Ramen noodles", "Pork bones", "Chashu pork", "Soft boiled egg", "Nori", "Green onion", "Bamboo shoots"]
  },
  {
    title: "Pad Thai",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800",
    video: "",
    discription: "Thai stir-fried noodles with shrimp and tamarind sauce",
    main_content: "rice noodles",
    cuisines: "thai",
    meals: "dinner",
    cookingtime: "25mins",
    servings: 2,
    note: "High heat wok is essential",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Soak rice noodles", "Stir-fry shrimp with garlic", "Add noodles and sauce", "Toss with bean sprouts", "Top with peanuts and lime"],
    ingredients: ["200g rice noodles", "200g shrimp", "Tamarind paste", "Fish sauce", "Bean sprouts", "Peanuts", "Eggs", "Lime"]
  },
  {
    title: "Green Curry",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800",
    video: "",
    discription: "Spicy Thai curry with coconut milk and basil",
    main_content: "chicken",
    cuisines: "thai",
    meals: "dinner",
    cookingtime: "30mins",
    servings: 4,
    note: "Adjust coconut milk for richness",
    rating: "⭐⭐⭐⭐",
    directions: ["Make green curry paste", "Fry paste in coconut cream", "Add chicken and vegetables", "Pour in remaining coconut milk", "Finish with Thai basil"],
    ingredients: ["400g chicken", "Green curry paste", "400ml coconut milk", "Thai eggplant", "Bamboo shoots", "Thai basil", "Fish sauce"]
  },
  {
    title: "Greek Moussaka",
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=800",
    video: "",
    discription: "Layered eggplant casserole with minced meat and cheese sauce",
    main_content: "eggplant",
    cuisines: "greek",
    meals: "dinner",
    cookingtime: "1.5 hrs",
    servings: 8,
    note: "Let it rest before serving",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Slice and salt eggplants", "Fry eggplant until golden", "Make meat sauce with tomatoes", "Layer eggplant and meat", "Top with bechamel and bake"],
    ingredients: ["3 eggplants", "500g minced lamb", "Tomato sauce", "Bechamel sauce", "Parmesan cheese", "Onion", "Garlic"]
  },
  {
    title: "German Pretzel",
    image: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=800",
    video: "",
    discription: "Soft pretzel with chewy center and crispy crust",
    main_content: "flour",
    cuisines: "german",
    meals: "snacks",
    cookingtime: "2 hrs",
    servings: 8,
    note: "Use baking soda bath for authentic color",
    rating: "⭐⭐⭐⭐",
    directions: ["Make yeast dough", "Rest for 1 hour", "Shape into pretzels", "Boil in baking soda water", "Bake at 425°F with butter"],
    ingredients: ["4 cups flour", "Yeast", "Baking soda", "Coarse salt", "Butter", "Sugar", "Warm water"]
  },
  {
    title: "Schnitzel",
    image: "https://images.unsplash.com/photo-1529566652340-2e8bfd15d3e4?w=800",
    video: "",
    discription: "Crispy breaded pork cutlet Viennese style",
    main_content: "pork",
    cuisines: "german",
    meals: "dinner",
    cookingtime: "30mins",
    servings: 4,
    note: "Pound meat thin for best results",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Pound pork cutlets thin", "Season with salt and pepper", "Dredge in flour, egg, breadcrumbs", "Fry in butter until golden", "Serve with lemon"],
    ingredients: ["4 pork cutlets", "Flour", "2 eggs", "Breadcrumbs", "Butter", "Lemon", "Parsley"]
  },
  {
    title: "French Onion Soup",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
    video: "",
    discription: "Rich beef broth with caramelized onions and melted cheese",
    main_content: "onions",
    cuisines: "french",
    meals: "lunch",
    cookingtime: "1 hr",
    servings: 4,
    note: "French bread and gruyere are essential",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Slice onions thin and caramelize for 30 mins", "Add beef broth and wine", "Simmer for 20 mins", "Ladle into oven-safe bowls", "Top with bread and gruyere, broil"],
    ingredients: ["4 large onions", "Beef broth", "Dry white wine", "French bread", "Gruyere cheese", "Butter", "Bay leaf", "Thyme"]
  },
  {
    title: "Coq au Vin",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800",
    video: "",
    discription: "Classic French braised chicken in red wine",
    main_content: "chicken",
    cuisines: "french",
    meals: "dinner",
    cookingtime: "1.5 hrs",
    servings: 6,
    note: "Use good quality wine",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Marinate chicken in wine overnight", "Brown chicken pieces", "Cook bacon and onions", "Braise everything together", "Reduce sauce and serve"],
    ingredients: ["1 whole chicken", "750ml red wine", "Bacon", "Pearl onions", "Mushrooms", "Chicken stock", "Thyme", "Bay leaf"]
  },
  {
    title: "Spanish Paella",
    image: "https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=800",
    video: "",
    discription: "Traditional rice dish with saffron and mixed seafood",
    main_content: "rice",
    cuisines: "spanish",
    meals: "dinner",
    cookingtime: "1 hr",
    servings: 6,
    note: "Never stir while cooking - let socarrat form",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Make sofrito with tomatoes", "Add rice and toast briefly", "Pour in saffron broth", "Arrange seafood on top", "Cook on low until liquid absorbed"],
    ingredients: ["2 cups bomba rice", "Saffron threads", "Shrimp", "Mussels", "Chicken", "Tomatoes", "Bell peppers", "Paprika"]
  },
  {
    title: "Gazpacho",
    image: "https://images.unsplash.com/photo-1529566652340-2e8bfd15d3e4?w=800",
    video: "",
    discription: "Refreshing chilled Spanish tomato soup",
    main_content: "tomatoes",
    cuisines: "spanish",
    meals: "lunch",
    cookingtime: "20mins",
    servings: 6,
    note: "Serve very cold",
    rating: "⭐⭐⭐⭐",
    directions: ["Blend tomatoes with vegetables", "Add bread and seasonings", "Blend until smooth", "Strain through sieve", "Chill for 2 hours"],
    ingredients: ["1kg ripe tomatoes", "1 cucumber", "1 green pepper", "2 cloves garlic", "Sherry vinegar", "Olive oil", "Bread"]
  },
  {
    title: "Turkish Kebab",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800",
    video: "",
    discription: "Grilled meat skewers with aromatic spices",
    main_content: "lamb",
    cuisines: "turkish",
    meals: "dinner",
    cookingtime: "45mins",
    servings: 4,
    note: "Best grilled over charcoal",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Ground lamb with spices", "Shape onto skewers", "Grill over high heat", "Serve with flatbread", "Top with tomatoes and parsley"],
    ingredients: ["500g ground lamb", "Onion", "Parsley", "Cumin", "Paprika", "Sumac", "Salt"]
  },
  {
    title: "Baklava",
    image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800",
    video: "",
    discription: "Sweet layered pastry with nuts and honey syrup",
    main_content: "phyllo",
    cuisines: "turkish",
    meals: "dessert",
    cookingtime: "1 hr",
    servings: 24,
    note: "Keep in airtight container",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Layer phyllo with butter", "Add nut mixture between layers", "Cut into diamond shapes", "Bake until golden", "Pour honey syrup while hot"],
    ingredients: ["1 package phyllo dough", "2 cups walnuts", "1 cup butter", "2 cups honey", "1 tsp cinnamon", "Cardamom"]
  },
  {
    title: "Adobo",
    image: "https://images.unsplash.com/photo-1617196034183-33d09fb30882?w=800",
    video: "",
    discription: "Filipino braised pork with vinegar and soy sauce",
    main_content: "pork",
    cuisines: "filipino",
    meals: "dinner",
    cookingtime: "1 hr",
    servings: 6,
    note: "Best eaten the next day",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Marinate pork in vinegar and soy", "Brown meat on all sides", "Add garlic and bay leaves", "Simmer until tender", "Reduce sauce until thick"],
    ingredients: ["500g pork belly", "Soy sauce", "Cane vinegar", "Garlic", "Bay leaves", "Black pepper", "Sugar"]
  },
  {
    title: "Sinigang",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
    video: "",
    discription: "Sour Filipino soup with tamarind and vegetables",
    main_content: "pork",
    cuisines: "filipino",
    meals: "lunch",
    cookingtime: "1.5 hrs",
    servings: 6,
    note: "Adjust sourness to taste",
    rating: "⭐⭐⭐⭐",
    directions: ["Boil pork until tender", "Add tamarind base", "Add vegetables", "Season with fish sauce", "Serve with rice"],
    ingredients: ["500g pork ribs", "Tamarind paste", "Water spinach", "Daikon", "Tomatoes", "Fish sauce", "Green chili"]
  },
  {
    title: "Chocolate Cake",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
    video: "",
    discription: "Rich and moist chocolate cake with layers of frosting",
    main_content: "chocolate",
    cuisines: "american",
    meals: "dessert",
    cookingtime: "1 hr",
    servings: 8,
    note: "Add frosting after completely cooling",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Mix flour, cocoa and baking powder", "Beat eggs and sugar until fluffy", "Add wet ingredients and mix", "Bake at 350°F for 30-35 mins", "Cool and frost with chocolate ganache"],
    ingredients: ["2 cups all-purpose flour", "1 cup cocoa powder", "1 cup sugar", "3 eggs", "1 cup butter", "1 cup milk", "Baking powder"]
  },
  {
    title: "BBQ Ribs",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
    video: "",
    discription: "Smoky American BBQ ribs with homemade sauce",
    main_content: "pork ribs",
    cuisines: "american",
    meals: "dinner",
    cookingtime: "3 hrs",
    servings: 4,
    note: "Low and slow is the key",
    rating: "⭐⭐⭐⭐⭐",
    directions: ["Remove membrane from ribs", "Apply dry rub", "Smoke at 225°F for 2 hours", "Wrap and cook 1 more hour", "Brush with BBQ sauce"],
    ingredients: ["2 racks pork ribs", "Brown sugar", "Paprika", "Garlic powder", "BBQ sauce", "Apple wood chips"]
  }
];

async function seed() {
  await client.connect();
  console.log("Connected to MongoDB");

  await client.db("kitchen").collection("recipe").deleteMany({});
  
  const result = await client.db("kitchen").collection("recipe").insertMany(sampleRecipes);
  console.log(`Added ${result.insertedCount} recipes!`);

  await client.close();
  console.log("Done!");
}

seed().catch(console.error);